apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tempconverter
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_DATABASE: "tempconverter"
  MYSQL_USER: "tempuser"
  MYSQL_PASSWORD: "temppass"
